import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../../styles/globals.css";
import { getLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { Header } from "../components/header";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = "";
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${theme} antialiased`}>
        <NextIntlClientProvider>
          <div className="flex h-screen">
            {/* <Sidebar /> */}
            <div className="flex-1 flex flex-col">
              <Header />
              {/* <!-- Content --> */}
              <main className="flex-1 overflow-y-auto">
                <div className="py-4 px-6 space-y-4">{children}</div>
              </main>
              {/* <!-- End Content --> */}
            </div>
          </div>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
