import type { Metadata } from "next";
import { Header } from "../components/header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="flex h-screen">
      {/* <Sidebar /> */}
      <div className="flex-1 flex flex-col">
        <Header />
        {/* <!-- Content --> */}
        <main className="flex-1 overflow-y-auto">
          <div className="py-4 px-6 space-y-4">{children}</div>
        </main>
        {/* <!-- End Content --> */}
      </div>
    </div>
  );
}
