import type { Metadata } from "next";
import { getLocale } from "next-intl/server";
import { Inter } from "next/font/google";
import "../styles/globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const theme = "";
  const locale = await getLocale();

  return (
    <html lang={locale}>
      <body className={`${inter.variable} ${theme} antialiased`}>
        {children}
      </body>
    </html>
  );
}
